### PR TITLE
chore: upgrade nodejs version for action, upgrade prod dependencies

### LINKED ISSUE #21: `Node.js 16 actions are deprecated` warning
Hi!

Can you please upgrade the Node version in action? Github is swearing at it.

image

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### PR DESCRIPTION
**Pull request by e965**
closes #21

### CODE REVIEW

**Comment by e965** [comment]
@dtinth review please 😉

**Comment by dtinth** [comment]
@e965 Many thanks for a PR, much appreciated! 🙏 🙏 

It appears some checks are failing. I looked through your fork but couldn't find a successful build within any workflow run. Could you resolve the build issues? I'd be happy to review it again afterwards.

**Comment by e965** [comment]
Hmm, that's weird. I was doing the work in github codespace and it was fine there. I'll check again.

**Comment by e965** [comment]
@dtinth can you please run workflows?

**Comment by dtinth** [comment]
@e965 I ran the workflow. I also temporarily updated the workflow approval settings so that as you add new commits to this PR, workflows should get run automatically without me having to approve it each time. 👍 

Thanks again for helping out with this project!

**Comment by e965** [comment]
@dtinth everything seems to be (finally) fine now

**Comment by dtinth** [comment]
I had a look. Everything looks great now, so I will go ahead and merge it. Thanks!!

**Comment by dtinth** [comment]
- [Released as v1.2.0](https://github.com/dtinth/setup-github-actions-caching-for-turbo/releases/tag/v1.2.0)

- [Verified that the new action works on a test repo](https://github.com/dtinth/turbo-caching-test/actions/runs/7658537554)

- Tag v1 has been force-pushed to point to v1.2.0

**Pull request merged**
